pipeline {
    agent any

    environment {
        APP_NAME = "coit-backend1"
        DEPLOY_DIR = "/var/lib/jenkins/apps"
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📥 Pulling code from Git...'
                git branch: 'develop', url: 'https://github.com/amolshete/coit-simple-microservice.git'
            }
        }

        stage('Build') {
            steps {
                echo '🔨 Building project with Maven.......'
                sh '''
                cd coit-backend1
                mvn clean package -DskipTests
                '''
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Running unit tests.......'
                sh '''
                cd coit-backend1
                mvn test
                '''
            }
        }

        // stage('Code Quality Check') {
        //     steps {
        //         echo '📊 Running SonarQube analysis...'
        //         // Requires SonarQube plugin + server configured in Jenkins
        //         withSonarQubeEnv('SonarQubeServer') {
        //             sh 'mvn sonar:sonar'
        //         }
        //     }
        // }

        stage('Package') {
            steps {
                echo '📦 Archiving JAR file...'
                archiveArtifacts artifacts: 'coit-backend1/target/*.jar', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo "🚀 Deploying ${APP_NAME}..."
                sh """
                    mkdir -p ${DEPLOY_DIR}
                    cp coit-backend1/target/*.jar ${DEPLOY_DIR}/${APP_NAME}.jar
                """
            }
        }
    }

    post {
        success {
            echo '✅ Build & Deployment successful!'
        }
        failure {
            echo '❌ Build failed. Please check logs.'
        }
    }
}
